BASE_URL = 'https://stellarburgers.nomoreparties.site'
CREATE_USER = '/api/auth/register'
LOGIN_USER = '/api/auth/login'
UPDATE_DATA = '/api/auth/user'
CREATE_ORDER = '/api/orders'
GET_ORDER = '/api/orders'
GET_INGREDIENTS = '/api/ingredients'
RESET_PASSWORD = '/api/password-reset'
RESET_PASSWORD_CONFIRM = '/api/password-reset/reset'
REGISTER_USER = '/api/auth/register'
LOGOUT_USER = '/api/auth/logout'
REFRESH_TOKEN = '/api/auth/token'
GET_USER_INFO = '/api/auth/user'
UPDATE_USER_INFO = '/api/auth/user'
DELETE_USER = '/api/auth/user'
GET_ALL_ORDERS = '/api/orders/all'
GET_USER_ORDERS = '/api/orders'



TEXT_USER_EXISTS = 'User already exists'
TEXT_EMPTY_FIELD = 'Email, password and name are required fields'
TEXT_INCORRECT_FIELD = 'email or password are incorrect'
TEXT_LOGIN_NEEDED = 'You should be authorised'


CREATE_USER_SUCCESS = 'success":true'
CREATE_USER_TWICE = 'User already exists'
CREATE_COURIER_WITHOUT_PASSWORD = 'Email, password and name are required fields"'
LOGIN_USER_SUCCESS = '"success":true'
INCORRECT_LOGIN_DATA = 'email or password are incorrect'
UPDATE_USER = 'success":true'
UPDATE_USER_UNSUCCESSFULLY = '"You should be authorised"'
CREATE_ORDER_SUCCESS = 'success":true'
CREATE_ORDER_WITHOUT_INGREDIENTS = 'Ingredient ids must be provided'
CREATE_ORDER_INCORRECT_INGREDIENT = 'Internal Server Error'
GET_ORDER_SUCCESS = 'success":true'
GET_ORDER_WITHOUT_AUTH = 'You should be authorised'


BUN_R2_D3 = '61c0c5a71d1f82001bdaaa6d'
MAIN_PROTOSTOMIA = '61c0c5a71d1f82001bdaaa6f'
SAUSE_SPICY_X = '61c0c5a71d1f82001bdaaa72'
INCORRECT_INGREDIENT = '6441d1f82abcd002172'
